
#include <assert.h>

#include <iostream>
#include <string>
#include <unordered_set>
#include <vector>

using std::cout;
using std::endl;
using std::string;
using std::unordered_set;
using std::vector;

class Solution {
 public:
  bool wordBreak(const string s, const vector<string> &wordDict) {
    const unordered_set words_coll(wordDict.cbegin(), wordDict.cend());
    vector result_table(s.size(), vector(s.size(), -1));
    for (int len = 1; len <= s.size(); ++len) {
      for (int i = 0; i + len - 1 < s.size(); ++i) {
        if (words_coll.count(string(s.data() + i, s.data() + i + len)) != 0) {
          result_table[i][i + len - 1] = 1;
          continue;
        }
        bool found_break_pos = false;
        for (int j = i + 1; j < i + len; ++j) {
          if (result_table[i][j - 1] == 1 && result_table[j][i + len - 1] == 1) {
            found_break_pos = true;
            break;
          }
        }
        if (found_break_pos)
          result_table[i][i + len - 1] = 1;
        else
          result_table[i][i + len - 1] = 0;
      }
    }
    return result_table[0][s.size() - 1] == 1;
  }
};

int main(void) {
  cout << "__cplusplus: " << __cplusplus << endl;
  // const string test_str("abc");
  // cout << string(test_str.data() + 0, test_str.data() + 1) << endl;
  // return 0;
  string str = "abcdefghijklmnopqrstuvwxyz";

  Solution sln;
  sln.wordBreak("aa", {"a"});
  bool rtn = sln.wordBreak("fohhemkkaecojceoaejkkoedkofhmohkcjmkggcmnami",
                           {"kfomka",
                            "hecagbngambii",
                            "anobmnikj",
                            "c",
                            "nnkmfelneemfgcl",
                            "ah",
                            "bgomgohl",
                            "lcbjbg",
                            "ebjfoiddndih",
                            "hjknoamjbfhckb",
                            "eioldlijmmla",
                            "nbekmcnakif",
                            "fgahmihodolmhbi",
                            "gnjfe",
                            "hk",
                            "b",
                            "jbfgm",
                            "ecojceoaejkkoed",
                            "cemodhmbcmgl",
                            "j",
                            "gdcnjj",
                            "kolaijoicbc",
                            "liibjjcini",
                            "lmbenj",
                            "eklingemgdjncaa",
                            "m",
                            "hkh",
                            "fblb",
                            "fk",
                            "nnfkfanaga",
                            "eldjml",
                            "iejn",
                            "gbmjfdooeeko",
                            "jafogijka",
                            "ngnfggojmhclkjd",
                            "bfagnfclg",
                            "imkeobcdidiifbm",
                            "ogeo",
                            "gicjog",
                            "cjnibenelm",
                            "ogoloc",
                            "edciifkaff",
                            "kbeeg",
                            "nebn",
                            "jdd",
                            "aeojhclmdn",
                            "dilbhl",
                            "dkk",
                            "bgmck",
                            "ohgkefkadonafg",
                            "labem",
                            "fheoglj",
                            "gkcanacfjfhogjc",
                            "eglkcddd",
                            "lelelihakeh",
                            "hhjijfiodfi",
                            "enehbibnhfjd",
                            "gkm",
                            "ggj",
                            "ag",
                            "hhhjogk",
                            "lllicdhihn",
                            "goakjjnk",
                            "lhbn",
                            "fhheedadamlnedh",
                            "bin",
                            "cl",
                            "ggjljjjf",
                            "fdcdaobhlhgj",
                            "nijlf",
                            "i",
                            "gaemagobjfc",
                            "dg",
                            "g",
                            "jhlelodgeekj",
                            "hcimohlni",
                            "fdoiohikhacgb",
                            "k",
                            "doiaigclm",
                            "bdfaoncbhfkdbjd",
                            "f",
                            "jaikbciac",
                            "cjgadmfoodmba",
                            "molokllh",
                            "gfkngeebnggo",
                            "lahd",
                            "n",
                            "ehfngoc",
                            "lejfcee",
                            "kofhmoh",
                            "cgda",
                            "de",
                            "kljnicikjeh",
                            "edomdbibhif",
                            "jehdkgmmofihdi",
                            "hifcjkloebel",
                            "gcghgbemjege",
                            "kobhhefbbb",
                            "aaikgaolhllhlm",
                            "akg",
                            "kmmikgkhnn",
                            "dnamfhaf",
                            "mjhj",
                            "ifadcgmgjaa",
                            "acnjehgkflgkd",
                            "bjj",
                            "maihjn",
                            "ojakklhl",
                            "ign",
                            "jhd",
                            "kndkhbebgh",
                            "amljjfeahcdlfdg",
                            "fnboolobch",
                            "gcclgcoaojc",
                            "kfokbbkllmcd",
                            "fec",
                            "dljma",
                            "noa",
                            "cfjie",
                            "fohhemkka",
                            "bfaldajf",
                            "nbk",
                            "kmbnjoalnhki",
                            "ccieabbnlhbjmj",
                            "nmacelialookal",
                            "hdlefnbmgklo",
                            "bfbblofk",
                            "doohocnadd",
                            "klmed",
                            "e",
                            "hkkcmbljlojkghm",
                            "jjiadlgf",
                            "ogadjhambjikce",
                            "bglghjndlk",
                            "gackokkbhj",
                            "oofohdogb",
                            "leiolllnjj",
                            "edekdnibja",
                            "gjhglilocif",
                            "ccfnfjalchc",
                            "gl",
                            "ihee",
                            "cfgccdmecem",
                            "mdmcdgjelhgk",
                            "laboglchdhbk",
                            "ajmiim",
                            "cebhalkngloae",
                            "hgohednmkahdi",
                            "ddiecjnkmgbbei",
                            "ajaengmcdlbk",
                            "kgg",
                            "ndchkjdn",
                            "heklaamafiomea",
                            "ehg",
                            "imelcifnhkae",
                            "hcgadilb",
                            "elndjcodnhcc",
                            "nkjd",
                            "gjnfkogkjeobo",
                            "eolega",
                            "lm",
                            "jddfkfbbbhia",
                            "cddmfeckheeo",
                            "bfnmaalmjdb",
                            "fbcg",
                            "ko",
                            "mojfj",
                            "kk",
                            "bbljjnnikdhg",
                            "l",
                            "calbc",
                            "mkekn",
                            "ejlhdk",
                            "hkebdiebecf",
                            "emhelbbda",
                            "mlba",
                            "ckjmih",
                            "odfacclfl",
                            "lgfjjbgookmnoe",
                            "begnkogf",
                            "gakojeblk",
                            "bfflcmdko",
                            "cfdclljcg",
                            "ho",
                            "fo",
                            "acmi",
                            "oemknmffgcio",
                            "mlkhk",
                            "kfhkndmdojhidg",
                            "ckfcibmnikn",
                            "dgoecamdliaeeoa",
                            "ocealkbbec",
                            "kbmmihb",
                            "ncikad",
                            "hi",
                            "nccjbnldneijc",
                            "hgiccigeehmdl",
                            "dlfmjhmioa",
                            "kmff",
                            "gfhkd",
                            "okiamg",
                            "ekdbamm",
                            "fc",
                            "neg",
                            "cfmo",
                            "ccgahikbbl",
                            "khhoc",
                            "elbg",
                            "cbghbacjbfm",
                            "jkagbmfgemjfg",
                            "ijceidhhajmja",
                            "imibemhdg",
                            "ja",
                            "idkfd",
                            "ndogdkjjkf",
                            "fhic",
                            "ooajkki",
                            "fdnjhh",
                            "ba",
                            "jdlnidngkfffbmi",
                            "jddjfnnjoidcnm",
                            "kghljjikbacd",
                            "idllbbn",
                            "d",
                            "mgkajbnjedeiee",
                            "fbllleanknmoomb",
                            "lom",
                            "kofjmmjm",
                            "mcdlbglonin",
                            "gcnboanh",
                            "fggii",
                            "fdkbmic",
                            "bbiln",
                            "cdjcjhonjgiagkb",
                            "kooenbeoongcle",
                            "cecnlfbaanckdkj",
                            "fejlmog",
                            "fanekdneoaammb",
                            "maojbcegdamn",
                            "bcmanmjdeabdo",
                            "amloj",
                            "adgoej",
                            "jh",
                            "fhf",
                            "cogdljlgek",
                            "o",
                            "joeiajlioggj",
                            "oncal",
                            "lbgg",
                            "elainnbffk",
                            "hbdi",
                            "femcanllndoh",
                            "ke",
                            "hmib",
                            "nagfahhljh",
                            "ibifdlfeechcbal",
                            "knec",
                            "oegfcghlgalcnno",
                            "abiefmjldmln",
                            "mlfglgni",
                            "jkofhjeb",
                            "ifjbneblfldjel",
                            "nahhcimkjhjgb",
                            "cdgkbn",
                            "nnklfbeecgedie",
                            "gmllmjbodhgllc",
                            "hogollongjo",
                            "fmoinacebll",
                            "fkngbganmh",
                            "jgdblmhlmfij",
                            "fkkdjknahamcfb",
                            "aieakdokibj",
                            "hddlcdiailhd",
                            "iajhmg",
                            "jenocgo",
                            "embdib",
                            "dghbmljjogka",
                            "bahcggjgmlf",
                            "fb",
                            "jldkcfom",
                            "mfi",
                            "kdkke",
                            "odhbl",
                            "jin",
                            "kcjmkggcmnami",
                            "kofig",
                            "bid",
                            "ohnohi",
                            "fcbojdgoaoa",
                            "dj",
                            "ifkbmbod",
                            "dhdedohlghk",
                            "nmkeakohicfdjf",
                            "ahbifnnoaldgbj",
                            "egldeibiinoac",
                            "iehfhjjjmil",
                            "bmeimi",
                            "ombngooicknel",
                            "lfdkngobmik",
                            "ifjcjkfnmgjcnmi",
                            "fmf",
                            "aoeaa",
                            "an",
                            "ffgddcjblehhggo",
                            "hijfdcchdilcl",
                            "hacbaamkhblnkk",
                            "najefebghcbkjfl",
                            "hcnnlogjfmmjcma",
                            "njgcogemlnohl",
                            "ihejh",
                            "ej",
                            "ofn",
                            "ggcklj",
                            "omah",
                            "hg",
                            "obk",
                            "giig",
                            "cklna",
                            "lihaiollfnem",
                            "ionlnlhjckf",
                            "cfdlijnmgjoebl",
                            "dloehimen",
                            "acggkacahfhkdne",
                            "iecd",
                            "gn",
                            "odgbnalk",
                            "ahfhcd",
                            "dghlag",
                            "bchfe",
                            "dldblmnbifnmlo",
                            "cffhbijal",
                            "dbddifnojfibha",
                            "mhh",
                            "cjjol",
                            "fed",
                            "bhcnf",
                            "ciiibbedklnnk",
                            "ikniooicmm",
                            "ejf",
                            "ammeennkcdgbjco",
                            "jmhmd",
                            "cek",
                            "bjbhcmda",
                            "kfjmhbf",
                            "chjmmnea",
                            "ifccifn",
                            "naedmco",
                            "iohchafbega",
                            "kjejfhbco",
                            "anlhhhhg"});
  assert(rtn);
  rtn = sln.wordBreak("leetcode", {"leet", "code"});
  assert(rtn);
  return 0;
}
